### ISSUE TITLE
abr "a>{click}+b{here}"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#13]
JS
```
<a href="">click<b>here</b></a>
```

Lazarus
```
<a href="|">click	<b>here</b></a>
```

@rickard67

**Comment by Alexey-T** [comment]
` the <b> element is placed inside <a> element. And that’s the difference: when {text} is written right after element, it doesn’t change parent context.`

**Comment by rickard67** [comment]
This was already fixed when fixing a previous issue. So, should work in v1.04.
