### ISSUE TITLE
abr "link>xsl:apply-templates"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#15]
JS (Emmet cheat sheet info)
```
<link rel="stylesheet" href="">
    <xsl:apply-templates></xsl:apply-templates>
</link>
```
Lazarus
```
<link rel="stylesheet" href="|" />
<xsl:apply-templates>|</xsl:apply-templates>
```

@rickard67

**Comment by rickard67** [comment]
I'm not sure about this one.

Visual Studio Code produces:
`<link rel="stylesheet" href="">
  <xsl:apply-templates></xsl:apply-templates>`

I'm not sure link should have an end tag
<link ... >
</link>

**Comment by Alexey-T** [comment]
Maybe Emmet doc outdated

**Comment by Alexey-T** [comment]
@sergeche cheat sheet docs maybe not ok.
