### ISSUE TITLE
Lorem dont work

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#16]
**lorem** is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.

You can specify how many words should be generated right in the abbreviation. For example, **lorem100** will generate a 100-words dummy text.

@rickard67

**Comment by Alexey-T** [comment]
https://docs.emmet.io/abbreviations/lorem-ipsum/

**Comment by rickard67** [comment]
I implemented it differently in TEmmet.

E.g.
**p{@lorem20}** gives

`<p>Lorem Ipsum tale libris! Ius! Rationibus habeo? Splendide volutpat senserit. Reprimique antiopam duis reprehendunt ancillae sem expetenda eum? Singulis? Epicuri.</p>`
