### ISSUE TITLE
CSS abbrev with "-"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#18]
Emmet’s CSS resolver has a nice feature that can greatly improve your CSS3 experience. Every time you precede CSS property or its abbreviation with a hyphen, Emmet automatically creates vendor-prefixed copies of this property. For example, -bdrs abbreviation will be expanded into

-webkit-border-radius: ;
-moz-border-radius: ;
border-radius: ;

===
I added "syntax" combobox to demo. I see abbr `-bdrs` don't work...
@rickard67

**Comment by rickard67** [comment]
I just implemented this differently in TEmmet.

This is from the RJ TextEd Emmet cheat sheet:

CSS
It's possible to use vendor prefix with abbreviations. E.g. -moz-ac will expand into -moz-align-content: |;

You can also use the macro prefixes -v-, -m-, -w- to expand into several lines with predefined vendor prefixes. Note that multi cursors are used to edit each line.

**-v-bb**
-webkit-border-bottom: |;
-moz-border-bottom: |;
border-bottom: |;

**-w-bb**
-webkit-border-bottom: |;
border-bottom: |;

**-m-bb**
-moz-border-bottom: |;
border-bottom: |;

**Comment by Alexey-T** [comment]
Maybe use standard way here? Ppl know it...

**Comment by rickard67** [comment]
- is the same as -v- in v1.04. So you can use -bdrs (or -v-bdrs).

**Comment by Alexey-T** [comment]
Maybe make it fully the same as original ?
