### ISSUE TITLE
Old delphi issues

### ISSUE THREAD

**Issue by rafaellop** [Alexey-T/Emmet-Pascal#20]
I couldn't compile the emmet.pas using Delphi 7. First the compiler tries to use the compatibility define for non-FPC IDE and errors are reported during build. For example the uses of `System.Dialogs` need to be just `Dialogs`. Then the `inline` directive for `pos()` is not recognized and a local function must be used instead (e.g. renamed to `locPos()`). Another issue is the `CharInSet()` function not available in Delphi 7. This can be fixed by a define and appropriate definition like below. It finally compiles after these changes.

```
function CharInSet(C : AnsiChar; const CharSet : TSysCharSet) : Boolean;
begin
	Result := C in CharSet;
end;
```

**Comment by rafaellop** [comment]
Update, finally I compiled the demo for Delphi, but it simply doesn't work for a simple abbreviation like `ul>li*5` and `html`.

**Comment by Alexey-T** [comment]
could you please go to RJ TextEd forum, and report bug there?
https://www.rj-texted.se/Forum/viewforum.php?f=22&

**Comment by Alexey-T** [comment]
RJ author doesnt reply to me, so i cannot report there.

**Comment by rafaellop** [comment]
Hi Alexey, thanks for your reply. I won't rather do it because I'll probably use the original emmet via node.
