### ISSUE TITLE
abbrev "form#search.wide"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#5]
https://docs.emmet.io/cheat-sheet/
JS gives
```
<form id="search" class="wide"></form>
```

Pascal gives
```
<form action="|" class="wide" id="search" ="">|</form>
```

**Comment by rickard67** [comment]
"form" is actually an abbreviation which expands to "<form action=""></form>" - so the pascal result is perfectly logical.

I just checked and Visual Studio Code expand the same string as TEmmet.

form#search.wide

gives

`<form action="" id="search" class="wide"></form>`

Made we should just leave it as is?

/Rickard Johansson

**Comment by Alexey-T** [comment]
The 1st post shows the bug: tail is ` =""`. equal sign without name.

**Comment by rickard67** [comment]
Ahh, I missed that one...

**Comment by rickard67** [comment]
Should work in v1.03.

**Comment by Alexey-T** [comment]
@sergeche Seems Emmet cheat sheet shows not ok (1st post)
