### ISSUE TITLE
abbrev "td[rowspan=2 colspan=3 title]"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#6]
JS gives
```
<td rowspan="2" colspan="3" title=""></td>
```
Pascal gives
```
<td rowspan="2" colspan="3" title="title">|</td>
```

**Comment by rickard67** [comment]
I think TStringlist.ValueFromIndex may work differently in Delphi and Free Pascal if a value can't be found. I made a minor change and it should work now in Lazarus as well, I hope.

/Rickard Johansson

**Comment by Alexey-T** [comment]
I can report to Laz bugtracker about it. What is the difference?

**Comment by Alexey-T** [comment]
I see what is diffe-ce. fixed, tks.

**Comment by Alexey-T** [comment]
@rickard67 Reported at https://bugs.freepascal.org/view.php?id=35660
