### ISSUE TITLE
abbrev "c"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/Emmet-Pascal#8]
JS gives
```
<!-- ${child} -->
```
Pas
```
<c>|</c>
```

**Comment by rickard67** [comment]
I've added 

`c=<!-- | -->`

to the snippets.ini file in v1.03.

I have a few more issues to fix in this version but will release it as soon as I get the time to fix them.

/Rickard Johansson

**Comment by Alexey-T** [comment]
Thanks
